name: ClickAuth
version: '${version}'
main: de.clickism.clickauth.ClickAuth
api-version: '1.20'
authors: [ Clickism ]
description: Simple player authentication plugin
commands:
  reset_password:
    description: Reset your or another player's password
    usage: /reset_password [player]
    permission: clickauth.reset_password.self
permissions:
  clickauth.reset_password.self:
    description: Allows players to reset their own password
    default: true
  clickauth.reset_password.others:
    description: Allows players to reset other players' passwords
    default: op
